server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /elsa-store/api
spring:
  application:
    name: elsa_store
  datasource:
    url: jdbc:mysql://localhost:3306/elsa_store_db
    username: root
<<<<<<< HEAD
    password: 123456
=======
    password: 03092003
>>>>>>> upstream/develop
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  signer-key: "6lhXE9HRxzm7EyIVWdl0XPx9eoGdgXm8VNfpaBQ1dUDpZF6NcF8z4fDAO15JFAdF" # Q8vU1eAgYjocmEtP
  valid-duration: 3600 # 1 tiếng
  refreshable-duration: 604800 # 7 ngày

file:
<<<<<<< HEAD
  upload-dir: uploads/
=======
  upload-dir: uploads/

vnpay:
  tmnCode : "KUHZ6TQJ"
  secretKey : "K20SB7Q7577Q70YWF5I512BL3IX95TP4"
  url : "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  returnUrl : "http://localhost:8080/elsa-store/api/payment/vn-pay-callback"
  version : "2.1.0"
  command : "pay"
  orderType : "other"
>>>>>>> upstream/develop
